//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjShoppingCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tServicelist
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> fServiceDate { get; set; }
        public Nullable<int> fServiceGuid { get; set; }
        public string fUserId { get; set; }
        public Nullable<int> fQuestionGuid { get; set; }
        public string fServiceEmail { get; set; }
        public string fServiceSort { get; set; }
        public string fServiceSub { get; set; }
        public string fServiceContent { get; set; }
    }
}
